server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        password: enter
        url: jdbc:postgresql://localhost:5432/marketplace
        username: postgres
#        hikari:
#            idle-timeout: 60000
#            maximum-pool-size: 5
#            connection-test-query: SELECT 1
#            pool-name: HikariCP
#            maximum-lifetime: 600000
#            max_tk_time: -1
#            leak-detection-threshold: 30000
#            close-on-jvm-shutdown: true

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB # set maximum file size limit
            max-request-size: 10MB # set maximum request size limit
            file-size-threshold: 2KB # set file size threshold

    mail:
        host: localhost
        port: 1025
        username: hello
        password: hello
        protocol: smtp
        properties.mail.smtp.auth: true
        properties.mail.smtp.starttls.enable: true
        properties.mail.smtp.ssl.trust: "*"
        properties.mail.smtp.connectiontimeout: 5000
        properties.mail.smtp.timeout: 3000
        properties.mail.smtp.writetimeout: 5000



#server:
#    error:
#        include-message: always
#        include-binding-errors: always
#
#spring:
#    datasource:
#        password: enter
#        url: jdbc:postgresql://localhost:5432/marketplace
#        username: postgres
#        hikari:
#            leak-detection-threshold: 30000
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
#                format_sql: true
#        show-sql: true
#    servlet:
#        multipart:
#            enabled: true
#            max-file-size: 10MB # set maximum file size limit
#            max-request-size: 10MB # set maximum request size limit
#            file-size-threshold: 2KB # set file size threshold
#
#    mail:
#        host: localhost
#        port: 1025
#        username: hello
#        password: hello
#
#        properties:
#            mail:
#                smtp:
#                    ssl:
#                        trust: "*"
#                    auth: true
#                    starttls:
#                        enable: true
#                    connectiontimeout: 5000
#                    timeout: 3000
#                    writetimeout: 5000
#
